#pragma once
#ifndef INCLUDE_FDB_EXCEPTION_H
#define INCLUDE_FDB_EXCEPTION_H

#include <stdexcept>
#include <future>
#include <cassert>
#include <string>

#define FDB_API_VERSION 200
#include <foundationdb/fdb_c.h>

/** @namespace fdb */
namespace fdb {

	/**
	 * Specialized exception for forwarding fdbc lib errors.
	 * 
	 * Provides a handler for error codes generated by the  C library and
	 * returns the human friendly error message.
	 */
    class exception : public std::runtime_error {
    public:
        explicit exception (fdb_error_t code);
        explicit exception (const std::string what);
    };
}

#endif